branches:
 only:
   - /\d+\.\d+.*/
language: go
go:
  - 1.7.x
env:
  global:
    - GOARCH=amd64
  matrix:
    - GOOS=linux
    - GOOS=darwin
script:
  - go build -o bin/hello-$GOOS-$GOARCH
deploy:
  provider: releases
  api_key:
    secure: 
  file_glob: true
  file: bin/*
  skip_cleanup: true
  on:
    tags: true
notifications:
  email:
    on_success: always
    on_failure: always
